import {css} from 'lit';

export default css`
    * {
        box-sizing: border-box;
    }

    :host {
        /* logo colors */
        --ua-gray: #4d4d4d;
        --ua-green: #39f746;

        /* Palette generated by Material Palette - materialpalette.com/light-green/grey */
        --dark-primary-color: #689f38;
        --default-primary-color: #8bc34a;
        --light-primary-color: #dcedc8;
        --accent-color: #9e9e9e;
        --text-color: #212121;
        --text-secondary-color: #757575;
        --border-color: #bdbdbd;

        /*
         * Override Vaadin
         */
        --lumo-primary-text-color: var(--dark-primary-color);
        --lumo-clickable-cursor: pointer;

        font-family: Lato, sans-serif;
    }

    h1,h2,h3,h4,h5,h6 {
        font-size: 2rem;
        margin: 0 0 15px;
        font-weight: 300;
    }

    h1 {
        margin: 8px 0 30px;
    }

    a {
        color: var(--lumo-primary-text-color);
    }

    img {
        max-width: 100%;
    }

    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 300px;
        min-height: 98px;
        padding: 10px 15px;
        margin-bottom: 25px;
        margin-right: 40px;
        background: var(--light-primary-color);
        text-align: left;
        border-radius: 3px;
    }

    /**** Responsive ****/
    @media (max-width: 810px) {
        .card {
            width: 90%;
            margin-right: 0;
            margin-bottom: 35px;
        }
    }
`;
